name: test-python-project

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

        wget -q https://github.com/dbradf/pypi-version-check/releases/download/v0.1.2/pypi-version-check
        chmod +x pypi-version-check

    - name: Test with pytest
      run: |
        poetry run pytest 

    - name: Test pypi version
      run: |
        ./pypi-version-check
    
    - name: Build docs
      working-directory: ./goodbase-docs
      run: |
        wget -q https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_0.92.1_Linux-64bit.tar.gz
        tar xf hugo_0.92.1_Linux-64bit.tar.gz
        ./hugo

